[package]
name = "variables"
version = "0.1.0"
authors = ["linuxbyes <real8686@gmail.com>"]
edition = "2.3.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
